name: project_netsurf
description: Much more from nature

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.0+51

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  shared_preferences: ^2.0.9
  synchronized: ^3.0.0
  pdf: ^3.10.4
  open_file_plus: ^3.4.1
  path_provider: ^2.0.7
  intl: ^0.18.1
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.1
  cached_network_image: ^3.2.0
  url_launcher: ^6.2.1
  package_info_plus: ^5.0.1
  flutter_phoenix: ^1.1.1
  share_plus: ^7.0.2
  firebase_analytics: ^10.4.3
  carousel_slider: ^4.0.0
  device_info_plus: ^9.0.2
  get_it: ^7.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/banner.png

dev_dependencies:
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1
#  flutter_app_name: ^0.1.0
  flutter_lints: ^3.0.1

flutter_native_splash:
  color: "#ffffff"
  image: assets/banner.png
  android: true
  ios: true
  web: true
# flutter pub run flutter_native_splash:create

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/banner.png"
# flutter pub run flutter_launcher_icons:main

flutter_launcher_name:
  name: "Netsurfs Calci"
# flutter pub run flutter_app_name
